name: '${name}'
main: '${group}.${name}'
loader: '${group}.support.DependencyLoader'

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

folia-supported: true